blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/GoogleCloudPlatform/flask-gae-starter/discussions
    about: Please ask questions and discuss ideas here
  - name: Security Issues
    url: https://github.com/GoogleCloudPlatform/flask-gae-starter/security/advisories/new
    about: Please report security vulnerabilities privately
